apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-prod
          image: gcr.io/project-1-400619/auth
          imagePullPolicy: Always
          
          ports:
            - containerPort: 3001